
services:
  postgres:
    build: .
    container_name: metamist_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-metamist}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-metamist_password}
      POSTGRES_DB: ${POSTGRES_DB:-metamist_db}
      DATABASE_URL: postgres://${POSTGRES_USER:-metamist}:${POSTGRES_PASSWORD:-metamist_password}@localhost:5432/${POSTGRES_DB:-metamist_db}?sslmode=disable&search_path=main
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - metamist_pg_data:/var/lib/postgresql
      - ./migrations:/db/migrations
volumes:
  metamist_pg_data:
