dev:
  - Changes do not contain the names of any sensitive CPG projects
  - Version number is bumped appropriately if API is changed
  - Tests cover any newly added code
  - There aren't any unnecessary autoformatting changes